# Generated by Django 5.1.5 on 2025-01-30 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companhia', models.CharField(max_length=100)),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('horario_partida', models.TimeField()),
                ('horario_chegada', models.TimeField()),
                ('data_voo', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comprador', models.CharField(max_length=200)),
                ('data_nasc', models.DateField()),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('ida', models.DateField()),
                ('volta', models.DateField(blank=True, null=True)),
                ('voo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voos.voo')),
            ],
        ),
    ]
